apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.labels.app }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
     app: {{ .Values.labels.app }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.labels.app }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: SECRET_KEY_1
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: secret-key-1
            - name: SECRET_KEY_2
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: secret-key-2
            - name: SECRET_KEY_3
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: secret-key-3
          volumeMounts:
            - name: {{ .Values.volumeMounts.name }}
              mountPath: {{ .Values.volumeMounts.mountPath }}
              subPath: {{ .Values.volumeMounts.subPath }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.configmap.name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1