apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "argocd-task1-chart.fullname" . }}
  labels:
    {{- include "argocd-task1-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
     app: {{ include "argocd-task1-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "argocd-task1-chart.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80