apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
spec:
  rules:
  - host: "dev.task.com"
    http:
      paths:
      - pathType: Prefix
        path: "/api"
        backend:
          service:
            name: {{ .Values.service.name }}
            port:
              number: 8080
      - pathType: Prefix
        path: "/logs"
        backend:
          service:
            name: {{ .Values.service.name }}
            port:
              number: 8081
      - pathType: Prefix
        path: "/soap"
        backend:
          service:
            name: {{ .Values.service.name }}
            port:
              number: 8082
  - host: "prd.task.com"
    http:
      paths:
      - pathType: Prefix
        path: "/api"
        backend:
          service:
            name: {{ .Values.service.name }}
            port:
              number: 8080
      - pathType: Prefix
        path: "/logs"
        backend:
          service:
            name: {{ .Values.service.name }}
            port:
              number: 8081
      - pathType: Prefix
        path: "/soap"
        backend:
          service:
            name: {{ .Values.service.name }}
            port:
              number: 8082
