apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  secret-key-1: {{ .Release.Name | randAlphaNum 16 | b64enc }}
  secret-key-2: {{ .Release.Name | randAlphaNum 16 | b64enc }}
  secret-key-3: {{ .Release.Name | randAlphaNum 16 | b64enc }}