apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.labels.app }}
  ports:
    - name: port-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: port-8081
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: port-8082
      protocol: TCP
      port: 8082
      targetPort: 8082
